README.md, examples/tests.rustpeg, src/fake_extctxt.rs
This evaluates to ^0.1.0 which is the way to define "semver compatible
version to 0.1.0". This fixes some issues with ~ and unstable (0.*)
versions and allows breaking changes in 0.x steps.
=> Use 0.1.0 as dependency range

examples/tests.rs, examples/tests.rustpeg, src/grammar.rs, src/grammar.rustpeg, src/translate.rs
Implements case insensitivity via the "i" flag after a quoted literal. e.g. "foo"i will match FOO,foo,FoO...etc.
Care was taken to ensure comparisons were utf8 safe.
Test cases created & tests all pass.
=> Implement case insensitivity via the "i" flag for quoted literals

src/peg.rs, src/peg_syntax_ext.rs
Rust is currently in the process of a complete overhaul of `std:io`. They moved the current `io` api to `std::old_io`. This pull request updates the three uses of `io` to `old_io` to keep rust-peg building on the nightly rustc.
=> Update all uses of std::io to use new std::old_io module

src/peg_syntax_ext.rs
Fixes 
```
/peg_syntax_ext.rs:104:35: 104:40 error: type `&syntax::parse::token::InternedString` does not implement any method in scope named `get`
```
=> Use deref instead of get on syntax::parse::token::InternedString

src/peg.rs, src/peg_syntax_ext.rs
`MacItems` was replaced by `MacEager`.
=> Fix compilation on current nightly

Cargo.toml, examples/test_errors.rs, src/grammar.rs, src/peg_syntax_ext.rs, src/translate.rs
A `ParseError` type is added to the generated parser module, containing the location in the input data that caused the error, as well as the set of expected items. If an error occurs, a `ParseError` is returned instead of a `String`. As a byproduct, parse errors now look nicer (since the `Display` implementation of `ParseError` does some custom formatting).
Note that the documentation wasn't yet updated to reflect this. Also, this is a breaking change (obviously), but since rust-peg is oriented towards the nightly builds, this should not be a big concern (this breakage can be easily fixed anyway).
=> Make parsers return a custom error type

src/grammar.rs, src/grammar.rustpeg, src/translate.rs, tests/test_conditional.rs
Adds special code blocks introduced with `{?`. They can cause the rule to fail by returning `Err(message)` and may be used to evaluate arbitrary constraints at match-time.
The conditional match block can also be used as a (very) awkward way of defining custom error messages:
```rust
_binop
= "+" / "-" / "*" / "/" / ">=" / "<=" / "==" / "!=" / ">" / "<"
binop
= op:_binop? {? match op {
Some(op) => Ok(op),
None => Err("binary operator"),
}}
```
When a parse error occurs at some place that expects a `binop`, only the string "binary operator" will be added to the expected set, instead of adding every single binary operator. Ideally, this would be properly supported (not requiring another rule and optional match) and have some syntax sugar to make it less verbose.
=> Conditional matching

src/grammar.rs, src/translate.rs
I noticed that the '^' was missing from error messages for character matches that are inverted. I've added a test and passed the invert bool to the format_char_set function to fix this. Let me know if this can be added or needs to be modified. Thanks for the great project!
=> Print '^' in inverted char set matches

src/grammar.rs, src/grammar.rustpeg, src/peg.rs, src/peg_syntax_ext.rs, src/translate.rs, tests/test_arithmetic.rs, tests/test_conditional.rs, tests/test_errors.rs, tests/tests.rs
Code generated by `rust-peg` no longer depends on the `collections` or `str_char` features, so it can be used on the beta.
=> Make generated code build on beta

src/grammar.rs, src/translate.rs
When the feature `peg_trace` is enabled, a trace message will be printed
whenever a function is entered or exited. Fixes #70.
=> Implement tracing

src/fake_extctxt.rs, src/rustast.rs
the syntax crate was refactored on nightly as per https://github.com/rust-lang/rust/commit/f786437bd223740d9767345731d458d10936f8d7
this makes rust-peg work again
=> fix to rust nightly 

benches/expr.rs, benches/expr.rustpeg, benches/json.rs, benches/json.rustpeg
I've added two simple benchmarks for performance testing: One is a JSON parser (might also make a decent example grammar), the other one parses arithmetic expressions with 4 operator precedence levels.
I hope this will prove useful when evaluating performance optimizations (memoization being the obvious one).
Benchmark results on my machine:
```
test expr ... bench:     15229 ns/iter (+/- 649) = 1 MB/s
test json ... bench:     25062 ns/iter (+/- 694) = 10 MB/s
```
Note that cargo does not show speeds below 1 MB/s, so a lower-end machine won't display them.
=> Add benchmarks

src/rustast.rs, src/translate.rs
Before:
```
tests/test_errors.rs:1:5: 1:11 error: no method named `len_` found for type `collections::vec::Vec<()>` in the current scope
tests/test_errors.rs:1 #![feature(plugin)]
^~~~~~
tests/test_errors.rs:1:1: 27:1 note: in expansion of peg!
tests/test_errors.rs:7:1: 11:5 note: expansion site
error: aborting due to previous error
tests/tests.rs:1:21: 1:28 error: no method named `uwrap` found for type `core::result::Result<_, _>` in the current scope
tests/tests.rs:1 #![feature(plugin, into_cow)]
^~~~~~~
tests/tests.rs:1:1: 92:1 note: in expansion of peg_file!
tests/tests.rs:6:1: 6:41 note: expansion site
```
(this was broken in other ways before, such as printing `name_123,ctxt_123` instead of identifiers)
After this change:
```
file:1:5: 1:11 error: no method named `len_` found for …
```
=> Fix error spans in PEG grammars

src/peg.rs, src/peg_syntax_ext.rs, src/rustast.rs, src/translate.rs
The `collections` feature was broken up into multiple finer-grained features. I've also replaced all uses of `.tail()` with `[1..]`, since `tail` might be renamed, and replaced `env::set_exit_status` with `process::exit`, since the former was deprecated.
This would break with the next nightly.
=> Use the new unstable features

src/grammar.rs, src/translate.rs, tests/tests.rs, tests/tests.rustpeg
A grammar like [a-zA-Z] ran with an input like "tt" would panic if the error was printed out.
=> Fixes bug where error's display panics when nothing more is expected from the input

Cargo.toml
=> Don't build the peg binary when benchmarking

src/grammar.rs, src/translate.rs, tests/test_memoization.rs
This didn't work before, since the `'input` lifetime wasn't declared
=> Allow caching 'input-bounded results

src/fake_extctxt.rs
hi! `rust-peg` no longer builds on rust nightly after [this commit](https://github.com/rust-lang/rust/commit/25cbb4385ee58804cb2483af56d1333fbee6e27d) rejiggered some rustc internals. I think this fixes it in a sane way, but I by no means know what I'm doing. `cargo test` still looks good, so I presume it's okay.
Is the goal to keep master building on nightly, or let them diverge and fix on new releases?
=> Update NameAndSpan after rustc refactor

src/fake_extctxt.rs, src/peg_syntax_ext.rs
Today's nightly build (June 20, 2016) shipped some libsyntax changes that broke this crate. Here's my stab at fixing the two compilation errors.
=> Support latest nightly

README.md
Since it is possible (as I found out by trial and as it is used in the source of the library itself), I think mentioning it in the documentation might be helpful.
=> Add section on comments in grammer.

README.md
I was looking for how to match a literal string ignoring case, and the only reference I could find was pull request #40. I figured it should probably be in the readme?
=> Add case insensitive literal expression to readme

src/translate.rs
When trying to compile a simple grammar with the using rust-peg with the Rust 2018 edition, I hit an error message:
```rust
error: expected expression, found reserved keyword `try`
```
In the code generated by rust-peg, I saw expressions like the following:
```rust
try ! ( write ! ( fmt , "error at {}:{}: expected " , self . line , self . column ) )
```
This is using the `try!` macro, which itself is fine and still works. The problem is the space between `try` and `!`, because it then `try` gets interpreted separately. This leads to the error, because `try` is a reserved keyword in the 2018 edition](https://github.com/rust-lang/rfcs/blob/master/text/2388-try-expr.md).
One could trim the spaces between `try` and `!`, but I don't know if that would mean a bigger change and if it would break …
=> Replace try with carrier operator

Cargo.toml, src/lib.rs, src/test.rs, src/translate.rs
This should close isssue #164, left recursion is now detected - both direct and indirect. An error message will be printed in the format `Found illegal left recursion for rule foo: foo -> bar -> foo`. The spans will also be underlined similarly to other errors, and the compilation will fail.
=> Add left recursion detection - Closes #164

README.md
I tried out the example, in the README but it didn't work, so I updated with a version that works with the latest master version of `peg`.
---
BTW I love the peg `parser!` macro. It is a *really* nice way to be able to quickly design a parser. Compared to the previous strategy of having `rustpeg` files it is way nicer because it is inside of a Rust file and automatically has the right syntax highlighting by the editor. Also, even though macros sometimes don't have the best experience inside of editors, a lot of the time, errors in my parser grammar were correctly identified and highlighted by RLS, which was nice.
Great job on peg!
=> Update Example in README

peg-macros/grammar.rs, peg-macros/grammar.rustpeg, tests/run-pass/crate_import.rs
=> Allow crate-relative imports in grammars

peg-runtime/lib.rs
This makes e.g. testing custom helpers returning `RuleResult`s easier,
as we can just
`assert_eq!(helper("foo"), RuleResult::Matched(3, expected))`.
=> Derive more Implementations for RuleResult

peg-macros/grammar.rs, peg-macros/grammar.rustpeg, tests/run-pass/arithmetic_ast.rs
Those seem to generate multiple `#[doc = "..."]` attributes, which are
only later concatenated into a single string.
=> Allow multiline doc-comments

peg-macros/ast.rs, peg-macros/grammar.rs, peg-macros/grammar.rustpeg, peg-macros/tokens.rs, peg-macros/translate.rs, tests/compile-fail/rust_action_type_error.stderr, tests/run-pass/conditional_block.rs
Allow `return` and `?` in the code block (#246), and prevent statements
like `break`/`continue` from messing up enclosing loops.
=> Wrap user-supplied code in immediately-invoked closure

peg-macros/grammar.rs, peg-macros/tokens.rs, peg-macros/translate.rs, peg-runtime/lib.rs, peg-runtime/slice.rs, peg-runtime/str.rs
Use Parse::is_eof() to replace the previous check for end-of-input.
Fixes #251
=> Add is_eof() function to Parse trait

peg-macros/grammar.rs, peg-macros/translate.rs, src/lib.rs, tests/run-pass/pattern.rs, tests/run-pass/tokens.rs
This changes the expansion of pattern expressions when used in a labeled
sequence such that the remainder of the sequence is lexically within the
match arm so that the variable is in scope.
Literal expressions are also included for the sake of generating nicer
code by not generating RuleResult in a `match` that is itself
immediately matched upon.
Fixes #227
=>  Add support for capturing variables from pattern expressions

peg-macros/ast.rs, peg-macros/grammar.rs, peg-macros/grammar.rustpeg, peg-macros/translate.rs, tests/run-pass/lifetimes.rs
This allows the parser to operate over types like `Token<'code>` by supplying the lifetime as a type parameter on the grammar (#220):
```rust
peg::parser! {
grammar feeny<'a>() for Tokens<'a> {
// snip
}
}
```
This should work with all type parameters, not just lifetimes, but lifetimes are the motivating example here.
Like @kevinmehall's comment on #220 suggests, this simply adds `rust_ty_params()` to `peg_grammar` in the meta-grammar, and then threads that through.
If a rule defines it's own type parameters, those come after the grammar's type parameters on the parser's exported functions/entrypoints.
=> Accept type parameters on grammar (e.g. lifetimes) (Fixes #220)

README.md, peg-macros/ast.rs, peg-macros/grammar.rs, peg-macros/grammar.rustpeg, peg-macros/translate.rs, src/lib.rs, tests/compile-fail/syntax_error.stderr, tests/run-pass/nonexhaustive.rs
I had a try at allowing nonexhaustive rules, as proposed in #179.
=> Allow nonexhaustive rules

peg-macros/grammar.rs, peg-macros/translate.rs, tests/run-pass/rule_args.rs
My use case is to parse a generic struct and require `FromStr` for that generic type.
```rust
struct Something<P>(P);
peg::parser! {
grammar mu_grammar() for str {
pub rule something<P: std::str::FromStr>() -> Something<P> {? ... }
}
}
```
The issue occurs because the current generated code assumes that `P` is provided as an argument to the rule, but in this case, it isn't and must be inferred by the return type. The change is to help type inferrence in one position.
=> fix: support generic argument in rule's return position

src/lib.rs
Formerly this example wouldn't parse single-letter identifiers, which might confuse someone using it directly.
If you'd like, another possible improvement is to make the doc test run and add the following to main:
```rust
fn main() {
doc::identifier("a").expect("a");
doc::identifier("foo1").expect("foo1");
doc::identifier("1up").expect_err("starts with number");
doc::identifier("hello there").expect_err("has a space");
}
```
=> Fix identifier example in top-level docs

peg-macros/grammar.rs, peg-macros/translate.rs
Part 2 of the #294 series, this PR just simply replace some `std` types that can use `core` as its substitution. This will greatly help `no_std` compatibility, although there are still some issue unresolved, for example, the `vec!` macro is subtlety used and this is undefined in `no_std` context -- although adding `use alloc::vec;` statement back in would compile well, but this would imply the use of `alloc`, and I think it is okay for most situations. 
My own anecdotal use case is for a core part of a language parser that I want it to be `no_std` so it can be embedded easily into a ESP32 target to parse some Lispy command from serial console for configurating sensor states and setup WiFi information in flash memory -- and I don't want to use LALR parser there because memory access time …
=> change some std types to core equivalent

peg-macros/ast.rs, peg-macros/grammar.rs, peg-macros/grammar.rustpeg, peg-macros/translate.rs, tests/run-pass/generic_fn_traits.rs, tests/run-pass/rule_where_clause.rs
close #370 
- Add where clause for rule fn
- Add some trailing comma support
- Add qualified-path-type support
=> Add where clause for rule fn, allow some rust syntax

peg-runtime/slice.rs, peg-runtime/str.rs
Trait impl methods need to be marked with #[inline] to allow cross-crate inlining.
As many of these functions are trivial, but they are called for every single position of the input, this has major impact:
- Performance of the new parse-rosetta-rs JSON parser example I recently contributed ([1]) increases by almost 40% on my machine, making it slightly faster than winnow (and possibly the fastest full-featured parser listed there)
- For a simple tokenizer I built for one of my projects, I measured a performance gain of ~94%, almost doubling the throughput!
[1] https://github.com/rosetta-rs/parse-rosetta-rs/blob/main/examples/peg-app/parser.rs
=> Allow inlining standard Parse* trait impls

peg-macros/grammar.rs, peg-macros/grammar.rustpeg, tests/run-pass/assembly_ast_dyn_type_param_bounds.rs
=> Fix type param bounds

peg-macros/translate.rs
`[PEG_TRACE] Cached fail of rule rule_name at 1:1`
to
`[PEG_TRACE] Cached fail of rule `rule_name` at 1:1`
=> Add quote for PEG_TRACE Cached
